import AppKit
import Carbon.HIToolbox

/// Delivers text into whatever app has focus by pasting it, then puts the user's clipboard back.
@MainActor
enum TextInserter {
    /// Marks our temporary clipboard write so clipboard managers (Raycast, Paste, Maccy) skip it.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func paste(_ text: String, restoreClipboard: Bool) {
        let board = NSPasteboard.general
        let saved = restoreClipboard ? snapshot(board) : nil

        board.clearContents()
        board.setString(text, forType: .string)
        board.setData(Data(), forType: transientType)
        board.setData(Data(), forType: concealedType)
        let ourChange = board.changeCount

        sendCommandV()

        guard let saved else { return }
        // Give the target app time to read the clipboard before restoring it. Skip the restore
        // if something else wrote to the clipboard in the meantime.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            guard board.changeCount == ourChange else { return }
            board.clearContents()
            if !saved.isEmpty { board.writeObjects(saved) }
        }
    }

    static func copy(_ text: String) {
        let board = NSPasteboard.general
        board.clearContents()
        board.setString(text, forType: .string)
    }

    private static func snapshot(_ board: NSPasteboard) -> [NSPasteboardItem] {
        (board.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private static func sendCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        // Ignore modifiers the user may still be holding so ⌥ doesn't turn ⌘V into ⌥⌘V.
        source?.setLocalEventsFilterDuringSuppressionState([.permitLocalMouseEvents, .permitSystemDefinedEvents], state: .eventSuppressionStateSuppressionInterval)
        let v = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cgAnnotatedSessionEventTap)
        up?.post(tap: .cgAnnotatedSessionEventTap)
    }
}
